GET http://localhost/PCplanet-Project/api/api.php?action=user-profile
Content-Type: application/json


###
POST http://localhost/PCplanet-Project/api/api.php?action=register-user
Content-Type: application/json

{
    "nome": "Mario323",
    "sobrenome": "abc32",
    "email": "mario@gmail.com3232312",
    "cpf": 12341233213,
    "rg": 123124312,
    "senha": "123453323"
}


###
POST http://localhost/PCplanet-Project/api/api.php?action=login-user
Content-Type: application/json

{
    "email": "mario@gmail.com3232312",
    "senha": "123453323"
}

###
POST http://localhost/PCplanet-Project/api/api.php?action=profile-user
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwY3BsYW5ldC1hZG1pbiIsImF1ZCI6InVzZXIiLCJpYXQiOjE3MTQyMzg5NzIsImV4cCI6MTcxNDQxMTc3MiwiaWQiOiIyMiJ9.cHgN-UFmSPQrySiHOUx1efkKM5GZJreQ0sLXt02oHeE






###
POST http://localhost/PCplanet-Project/api/api.php?action=profile-user-edit
Content-Type: application/json

{
    "senhaNova": "321332132321321",
    "senhaAtual": "123456",
    "email": "dudukof110@gmail.com"
}